main:
  - identifier: blog
    name: Blog
    weight: 40
    params:
      icon:
        vendor: fas
        name: blog

  - name: Support
    identifier: support
    weight: 100
    url: https://github.com/sudiaty
    params:
      header: The SinoDawn support community.
      icon:
        vendor: font-awesome-solid
        name: headset
